### ISSUE TITLE
Unable to get data from the vercel

### ISSUE THREAD

**Issue by ramanujamgond** [novatorem/spotify-readme#5]
Hello Andrew,

I tried to implement your Spotify-readme app on my repo readme file. But how many times I tried I am not getting any response from the vercel server. I followed all the instructions from the SetUp.md file. I have set the client Id client secret and refresh token but still, I am the internal server error. I don't know where I am doing wrong. Any help would be much appreciated. Thank you

Error - Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Below are the lines of code that I am using in the readme.md file

### Spotify Playing 🎧
[<img src="https://spotify-readme.ramanujamgond.vercel.app/api/spotify-playing" alt="string1301 spotify playing" width="350" />](https://open.spotify.com/user/989umq8v9mzt065wlcbmaqgz0)

**Comment by novatorem** [comment]
I think you have a set of permission problems.

One, if you're linking up your vercel to your readme: 
https://github.com/ramanujamgond/ramanujamgond

It would have taken the repository above, but it looks like it doesn't have the api there.
Looking at your vercel app: https://spotify-readme.ramanujamgond.vercel.app/

It's actually still linked to my github repository.
So make sure you configure vercel properly and copy the rest of the files in /api/ to your own ramanujamgond/ramanujamgond.

**Comment by ramanujamgond** [comment]
But I have imported the repo which I forked from your account. Can you please elaborate a little bit so that I can track down the error.

**Update** 
Thank you @novatorem (Andrew). Finally, I was able to fix the error you were right I was doing it in wrong way. I have not included my repo in Vercel. I just pointed the forked repo form your account. 

Anyway, thank you so much for your fast response.
