### ISSUE TITLE
{"error":"invalid_client"}

### ISSUE THREAD

**Issue by kutemeikito** [novatorem/spotify-readme#6]
Can you help me sar??
i'm tried to curl the command.
the default curl command is 
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: Basic {BASE64}" -d "grant_type=authorization_code&redirect_uri=http://localhost/callback/&code={CODE}" https://accounts.spotify.com/api/token

and i change the "BASE64" with mine and also the Callback "CODE"

i got this {"error":"invalid_client"}

What's Wrong??

**Comment by novatorem** [comment]
Use the newer version, with a better guide here: https://github.com/novatorem/novatorem
